repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.13
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-pytest
  #   rev: v8.2.1  # match your local pytest version
  #   hooks:
  #     - id: pytest
  #       name: run-pytest
  #       args: ["--maxfail=1", "--disable-warnings"]