# Generated by Django 5.2.4 on 2025-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', verbose_name='Status'),
        ),
    ]
